### ISSUE TITLE
cannot precomile

### ISSUE THREAD

**Issue by fieker** [oscar-system/Polymake.jl#327] opened 2020-11-02 14:13 UTC
[ Info: Generating module matroid
ERROR: LoadError: InitError: MethodError: no method matching String(::Base.RefValue{String})
Closest candidates are:
  String(::String) at boot.jl:321
  String(::Array{UInt8,1}) at strings/string.jl:39
  String(::Base.CodeUnits{UInt8,String}) at strings/string.jl:77
  ...
Stacktrace:
 [1] __init__() at /home/fieker/.julia/packages/Polymake/Zj1DQ/src/Polymake.jl:99
 [2] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697

**Comment by benlorenz** [comment] 2020-11-02 14:21
duplicate of #328

**Closed by benlorenz** 2020-11-02 14:21 UTC
