### ISSUE TITLE
Signal handling

### ISSUE THREAD

**Issue by fieker** [oscar-system/Polymake.jl#330] opened 2020-11-03 13:40 UTC

**Comment by fieker** [comment] 2020-11-03 13:41
Sorry, clicked wrong, but:
julia> using Revise, Hecke

julia> crt(fmpz[1073741826,6], fmpz[491128050, 0])
ERROR: DivideError: integer division error
Stacktrace:
 [1] crt(::fmpz, ::fmpz, ::fmpz, ::fmpz, ::Bool) at /home/fieker/.julia/dev/Nemo/src/flint/fmpz.jl:869


due to stupid input. Fine, but:
julia> using Polymakejulia> crt(fmpz[1073741826,6], fmpz[491128050, 0])
Floating exception (core dumped)

... and back to the unix shell ...

It would be good if the signal handler would still catch the division error.

**Comment by kalmarek** [comment] 2020-11-03 14:01
Since neither `crt` nor `fmpz` are touched by `Polymake`, I'd guess that the issue belongs to `LoadFlint`, i.e. some conflicting initialization of flint?

**Comment by fieker** [comment] 2020-11-03 14:05
no, its changing of signal handlers I'd guess. Prior to using Polymake, the SIGFPE is caught by Julia (or flint or?), but after using Polymake it is not handled at all

**Comment by kalmarek** [comment] 2020-11-03 14:19
@benlorenz is the expert here ;)

**Comment by benlorenz** [comment] 2020-11-03 18:03
I am quite sure that polymake does not mess with the FPE handler.
But it is quite possible that perl touches it, which means I need to dig around a bit to find where this happens and if we can avoid it. (I can reproduce it here)

**Comment by benlorenz** [comment] 2020-11-25 23:55
This should be fixed with the new Perl_jll rebuild, version 5.30.3+2, which should be pulled in with the next `]up`.

**Closed by benlorenz** 2020-11-25 23:55 UTC
